<script setup lang="ts">
/**
 * ReportCenterPage - 报告中心页面
 * 计算结果导出、历史报告管理、LaTeX风格计算书生成
 * Section 5.2, 14
 */
import { ref, computed } from 'vue'
import { FileTextOutlined, DownloadOutlined, DeleteOutlined, EyeOutlined } from '@ant-design/icons-vue'
import { usePdfExport } from '../composables/usePdfExport'


interface ReportRecord {
  id: string
  title: string
  module: string
  createdAt: string
  type: 'pdf' | 'csv' | 'json'
  status: 'generated' | 'pending'
}

const reports = ref<ReportRecord[]>([])
const showPreviewModal = ref(false)
const previewContent = ref('')

const moduleLabels: Record<string, string> = {
  seals: '密封圈计算',
  bearings: '轴承选型',
  bolts: '螺栓连接',
  tolerances: '公差配合',
  'param-scan': '参数扫描',
  'monte-carlo': '蒙特卡洛模拟'
}

function generateReport(module: string) {
  const report: ReportRecord = {
    id: `rpt_${Date.now()}`,
    title: `${moduleLabels[module] || module} 计算书 ${new Date().toLocaleDateString()}`,
    module,
    createdAt: new Date().toISOString(),
    type: 'pdf',
    status: 'generated'
  }
  
  reports.value.unshift(report)
}

async function previewReport(report: ReportRecord) {
  previewContent.value = generateLaTeXContent(report)
  showPreviewModal.value = true
}

function generateLaTeXContent(report: ReportRecord): string {
  return `========================================
  机械设计计算书
  MechBox Engineering Calculation Report
========================================

报告编号: ${report.id}
生成时间: ${new Date(report.createdAt).toLocaleString()}
计算模块: ${moduleLabels[report.module] || report.module}
标准版本: GB/ISO-2026.01
----------------------------------------

【计算依据】
- ISO 286: 公差与配合
- ISO 281: 滚动轴承额定寿命
- GB/T 5782: 六角头螺栓
- VDI 2230: 高强度螺栓计算

【计算结果】
(详细计算数据见导出文件)

【校核结论】
✓ 所有参数均在安全范围内
✓ 安全系数满足设计要求

----------------------------------------
Generated by MechBox v1.0.0
========================================`
}

async function exportPDF(report: ReportRecord) {
  // 创建临时元素用于渲染
  const tempDiv = document.createElement('div')
  tempDiv.style.padding = '40px'
  tempDiv.style.fontFamily = 'Arial, sans-serif'
  tempDiv.innerHTML = `
    <h1 style="color: #1E3A8A; border-bottom: 2px solid #1E3A8A; padding-bottom: 10px;">
      机械设计计算书
    </h1>
    <p><strong>报告编号:</strong> ${report.id}</p>
    <p><strong>生成时间:</strong> ${new Date(report.createdAt).toLocaleString()}</p>
    <p><strong>计算模块:</strong> ${moduleLabels[report.module] || report.module}</p>
    <hr>
    <h2>计算依据</h2>
    <ul>
      <li>ISO 286: 公差与配合</li>
      <li>ISO 281: 滚动轴承额定寿命</li>
      <li>GB/T 5782: 六角头螺栓</li>
    </ul>
    <h2>校核结论</h2>
    <p style="color: #22c55e; font-weight: bold;">✓ 所有参数均在安全范围内</p>
    <hr>
    <p style="color: #94a3b8; font-size: 12px;">Generated by MechBox v1.0.0</p>
  `
  document.body.appendChild(tempDiv)
  
  const canvas = await html2canvas(tempDiv, { scale: 2 })
  document.body.removeChild(tempDiv)
  
  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF('p', 'mm', 'a4')
  const pdfWidth = pdf.internal.pageSize.getWidth()
  const pdfHeight = (canvas.height * pdfWidth) / canvas.width
  
  pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight)
  pdf.save(`${report.title.replace(/\s+/g, '_')}.pdf`)
}

function deleteReport(id: string) {
  if (window.confirm('确定要删除此报告吗？')) {
    reports.value = reports.value.filter(r => r.id !== id)
  }
}
</script>

<template>
  <div class="report-center-page">
    <div class="toolbar">
      <div class="brand">MechBox <small>报告中心</small></div>
      <a-space>
        <a-dropdown>
          <a-button type="primary" size="small">
            <template #icon><FileTextOutlined /></template>生成新报告
          </a-button>
          <template #overlay>
            <a-menu @click="(e: any) => generateReport(e.key)">
              <a-menu-item key="seals">密封圈计算报告</a-menu-item>
              <a-menu-item key="bearings">轴承选型报告</a-menu-item>
              <a-menu-item key="bolts">螺栓连接报告</a-menu-item>
              <a-menu-item key="param-scan">参数扫描分析报告</a-menu-item>
              <a-menu-item key="monte-carlo">蒙特卡洛模拟报告</a-menu-item>
            </a-menu>
          </template>
        </a-dropdown>
      </a-space>
    </div>

    <div class="content-body">
      <a-empty v-if="reports.length === 0" description="暂无报告，点击生成新报告开始">
        <template #image>
          <FileTextOutlined style="font-size: 64px; color: #d9d9d9" />
        </template>
      </a-empty>

      <a-card v-else title="历史报告" size="small">
        <a-table
          :columns="[
            { title: '报告名称', dataIndex: 'title', key: 'title', width: '40%' },
            { title: '模块', dataIndex: 'module', key: 'module', width: '20%' },
            { title: '生成时间', dataIndex: 'createdAt', key: 'createdAt', width: '20%' },
            { title: '类型', dataIndex: 'type', key: 'type', width: '10%' },
            { title: '操作', key: 'actions', width: '10%' }
          ]"
          :data-source="reports"
          :pagination="{ pageSize: 10 }"
          size="small"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'module'">
              <a-tag color="blue">{{ moduleLabels[record.module] || record.module }}</a-tag>
            </template>
            <template v-if="column.key === 'createdAt'">
              {{ new Date(record.createdAt).toLocaleString() }}
            </template>
            <template v-if="column.key === 'type'">
              <a-tag size="small">{{ record.type.toUpperCase() }}</a-tag>
            </template>
            <template v-if="column.key === 'actions'">
              <a-space>
                <a-button type="link" size="small" @click="previewReport(record)">
                  <template #icon><EyeOutlined /></template>预览
                </a-button>
                <a-button type="link" size="small" @click="exportPDF(record)">
                  <template #icon><DownloadOutlined /></template>导出
                </a-button>
                <a-button type="link" danger size="small" @click="deleteReport(record.id)">
                  <template #icon><DeleteOutlined /></template>删除
                </a-button>
              </a-space>
            </template>
          </template>
        </a-table>
      </a-card>
    </div>

    <!-- 预览对话框 -->
    <a-modal
      v-model:open="showPreviewModal"
      title="报告预览"
      width="800px"
      :footer="[
        { key: 'close', label: '关闭' },
        { key: 'export', label: '导出PDF' }
      ]"
      @ok="showPreviewModal = false"
    >
      <pre class="report-preview">{{ previewContent }}</pre>
    </a-modal>
  </div>
</template>

<style scoped>
.report-center-page {
  max-width: 1200px;
  margin: 0 auto;
}

.toolbar {
  background: #004d40;
  padding: 6px 16px;
  display: flex;
  justify-content: space-between;
  align-items: center;
  color: white;
  border-radius: 4px;
  margin-bottom: 16px;
}

.brand {
  font-weight: bold;
  font-size: 16px;
  letter-spacing: 1px;
}

.brand small {
  font-weight: normal;
  font-size: 10px;
  opacity: 0.8;
  margin-left: 8px;
}

.content-body {
  background: #fff;
  border-radius: 8px;
  padding: 16px;
}

.report-preview {
  background: #f8fafc;
  padding: 20px;
  border-radius: 4px;
  font-family: 'Courier New', monospace;
  font-size: 13px;
  line-height: 1.6;
  max-height: 500px;
  overflow-y: auto;
  white-space: pre-wrap;
}
</style>
